name: Build on Changes
on:
  push:
    branches: [ '!main' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: '[{"id": "github", "username": "klcodanr", "password": "${{ secrets.GH_PAT }}"}]'
        apacheSnapshots: true
        sonatypeSnapshots: true
    - name: Build with Maven
      run: mvn -B install --file pom.xml
